services:
  api_service:
    build: .
    restart: always
    environment:
      - SPRING.DATA.MONGODB.HOST=mongo_db
      - SPRING.DATA.MONGODB.PORT=27017
      - SPRING.DATA.MONGODB.DATABASE=wishlistDB
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
  mongo_db:
    image: "mongo:4.4.3"
    restart: always
    ports:
      - 27017:27017